export const QueryKeys = {
  Login: 'Login',
  VerifyOTP: 'VerifyOTP',
  DeviceList: 'DeviceList',
  UserList: 'UserList',
  DeviceDetails: 'DeviceDetails',
  UserDetail: 'UserDetail',
  DeviceDetailsUpdate: 'DeviceDetailsUpdate',
  AssignUser: "AssignUser",
  NotificationPreference: "NOTIFICATION_PREFERENCE",
  RchargeRequest: "RchargeRequest",
  AssignDevice: "AssignDevice",
  AddUser: "AddUser",
  EditUser: "EditUser",
  DeleteAccount: "DeleteAccount",
  DeleteDelete: "DeleteDelete",
  getNotificationList: "getNotificationList",
  DeleteUser: "DELETE_USER",
  DeviceControl: "DeviceControl"
};
